services:
  frontend:
    image: ryanmalonzo/classicwheels-frontend
    container_name: classicwheels-frontend
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: ryanmalonzo/classicwheels-api
    container_name: classicwheels-api

  db:
    image: postgres:17
    container_name: classicwheels-db
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_USER: swarm
      POSTGRES_PASSWORD: swarm
      POSTGRES_DB: ecommerce

  adminer:
    image: adminer
    container_name: classicwheels-adminer
    ports:
      - "8080:8080"

volumes:
  postgres:
