services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.33
      resources:
        limits:
          cpus: '0.25'
      placement:
        preferences:
          - spread: node.id

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.33
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'
      placement:
        preferences:
          - spread: node.id

  db:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
