services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - frontend
      - api

  frontend:
    command: sh -c "npm i && npm run build"
    volumes:
      - "./frontend:/home/node/app"
      - frontend_build:/home/node/app/dist
    ports: []

  api:
    command: sh -c "npm i && npm start"

volumes:
  frontend_build:
